var lab = Array();
//
var thislab = [];
lab.push(thislab);
thislab.push("                        +-W-+-W-+                            ");
thislab.push("                        W H   H W                            ");
thislab.push("+---+---+---+---+---+---+       +---+---+---+---+---+---+---+");
thislab.push("| H   H   H   H   H |     H   H                     D T     +");
thislab.push("+                   +                               +       +");
thislab.push("W                   D     H   H                   A W       +");
thislab.push("+                   +                               +       +");
thislab.push("| H   H   H   H   H |                             A W       +");
thislab.push("+-------------------+                               +       +");
thislab.push("+         A   A   A |                             A W       +");
thislab.push("+                   +   +---+---+---+               +       +");
thislab.push("W                   |   |         H +             A W       +");
thislab.push("+                   +   +           +---+---+---+---+-D-+   +");
thislab.push("W                   D   D H         +     A   A   A     |   +");
thislab.push("+                   +   +---+---+---+                   +   +");
thislab.push("W                   +           D                       W   +");
thislab.push("+---+---+---+---+---+   +---+-D-+---+                   |   +");
thislab.push("W         A   A   Z |   +         H |                   W   +");
thislab.push("+                   +   +           +                   |   +");
thislab.push("W                   D   +         H |                   W   +");
thislab.push("+                   +   +           +                   |   +");
thislab.push("W                   |   + A   H   H |                   |   +");
thislab.push("+---+---+---+---+---+-D-+-----------+---+---+---+---+-------+");
thislab.push("W   |                   W                     Z9            |");
thislab.push("+   +---+---+---+---+   +                                   +");
thislab.push("W E   M   L           Z9D                                   |");
thislab.push("+---+---+---+---+---+---+-----------------------------------+");
//
var thislab = [];
lab.push(thislab);
thislab.push("+---+---+-------+---+---+---+---+---+");
thislab.push("+ E   M   A   L + Z1              T +");
thislab.push("+---+---+       +---+---+   +---+---+");
thislab.push("+ A             D                 H +");
thislab.push("+---+---+---+---+---+---+---+---+---+");
//
var thislab = [];
lab.push(thislab);
thislab.push("+---+---+---+---+---+---+---+---+---+---+");
thislab.push("+                                       +");
thislab.push("+                       +---+---+---+   +");
thislab.push("+                       D     Z1  T +   +");
thislab.push("+                       +---+   +---+   +");
thislab.push("+         L                 +   + A     +");
thislab.push("+---+---+                   +   +---+   +");
thislab.push("+     M                     +     H +   +");
thislab.push("+                           +---+---+   +");
thislab.push("+ E                                     +");
thislab.push("+---+---+---+---+---+---+---+---+---+---+");
//
var thislab = [];
lab.push(thislab);
thislab.push("+---+---+---+---+---+---+---+---+---+---+");
thislab.push("+                   +                 L +");
thislab.push("+                   +   +---+   +---+   +");
thislab.push("+                   +   +     Z2    +   +");
thislab.push("+                   +   +---+   +---+   +");
thislab.push("+ A                 +     H +   +       +");
thislab.push("+---+---+       +---+       +   +---+   +");
thislab.push("+ E   M +     L +           +     T +   +");
thislab.push("+       +       +           +---+---+   +");
thislab.push("+       D                               +");
thislab.push("+---+---+---+---+---+---+---+---+---+---+");
//
var thislab = [];
lab.push(thislab);
thislab.push("+---+---+---+---+---+---+---+---+---+---+");
thislab.push("+                   +                 L +");
thislab.push("+   +---+   +---+   +   +---+   +---+   +");
thislab.push("+   +   +   +   +   +   +   +   +   +   +");
thislab.push("+   +---+   +---+   +   +---+   +---+   +");
thislab.push("+                                       +");
thislab.push("+   +---+---+   +---+---+   +---+---+   +");
thislab.push("+   +       +   +       +   +       +   +");
thislab.push("+   +---+---+   +---+---+   +---+---+   +");
thislab.push("+                                       +");
thislab.push("+           +   +       +   +           +");
thislab.push("+           +   +       +   +           +");
thislab.push("+           +   +       +   +           +");
thislab.push("+ E   M     D   + Z6  T +   +           +");
thislab.push("+---+---+   +   +-------+   +   +---+---+");
thislab.push("        +   +               +   +       +");
thislab.push("+---+---+   +   +-------+   +   +---+   +");
thislab.push("+           +   +       +   +           +");
thislab.push("+   +---+---+   +       +   +---+---+   +");
thislab.push("+   + H                           H +   +");
thislab.push("+   +---+---+---+---+---+---+---+---+   +");
thislab.push("+                                       +");
thislab.push("+---+---+---+---+---+---+---+---+---+---+");
